import silkreportgenerator as rg
import unittest
import numpy as np
import os
import shutil

class TestReportGenerator(unittest.TestCase):
  def setUp(self):
    self.mOutputDir         = "./generator_output"
    self.mIndexSourceDir    = "./sample/generator/has_index"
    self.mNoIndexSourceDir  = "./sample/generator/no_index"
    self.mPattern           = "./sample/testpattern_pass.pattern"
    pass

  def tearDown(self):
    # Clean output folder generated by test cases
    if True == os.path.exists(self.mOutputDir):
      shutil.rmtree(self.mOutputDir)
    pass

  def testPopulateSourceFiles(self):

    # There are three log file in this folder. Only two of them listed in index file.
    # Generator should only gather files which listed in index file
    generator = rg.SilkReportGenerator()
    self.failIf(False ==
        generator._PopulateSourceFiles(self.mIndexSourceDir))
    self.failIf(2 != len(generator.mFileList))

    # There are three log files and one txt file in /sample/generator/no_index
    # folder.
    # Generator should only collect *.log files.
    generator = rg.SilkReportGenerator()
    self.failIf(False ==
        generator._PopulateSourceFiles(self.mNoIndexSourceDir))
    self.failIf(3 != len(generator.mFileList))

  def testGenerateReport(self):
    # Give wrong pattern file.
    if True == os.path.exists(self.mOutputDir):
      shutil.rmtree(self.mOutputDir)

    generator = rg.SilkReportGenerator()
    generator._PopulateSourceFiles(self.mIndexSourceDir)
    files = generator.mFileList
    self.failIf(True == generator._GenerateReport("./not__exist__file.pattern",
                                                  files, self.mOutputDir, (0, 0)))

    # Generte figures from a valid folder with index file
    if True == os.path.exists(self.mOutputDir):
      shutil.rmtree(self.mOutputDir)

    generator = rg.SilkReportGenerator()
    generator._PopulateSourceFiles(self.mIndexSourceDir)
    files = generator.mFileList
    # Expect 2 figures + 1 statistic file
    outputNumber = len(files) + 1
    self.failIf(False == generator._GenerateReport(self.mPattern,
                                                   files, self.mOutputDir, (0, 0)))
    self.failIf(outputNumber != len([f for f in os.listdir(self.mOutputDir)]))

    shutil.rmtree(self.mOutputDir)

  def testRun(self):
    # Input wrong pattern file.
    if True == os.path.exists(self.mOutputDir):
      shutil.rmtree(self.mOutputDir)

    generator = rg.SilkReportGenerator()
    self.failIf(generator.Run(self.mPattern, self.mOutputDir, self.mNoIndexSourceDir))

    # There are three log files in sourceDir. Two of them are valide log
    # Should generate 2 figures and a statistic file.
    self.failIf(3 != len([f for f in os.listdir(self.mOutputDir)]))

    shutil.rmtree(self.mOutputDir)

# Run the unittests
if __name__ == '__main__':
   unittest.main()
